---
- name: Provision aws oracle rds
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:
  - name: Launch RDS instances
    rds:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      command: create
      instance_name: oraclelinkstardb
      db_engine: oracle-se
      instance_type: db.t2.micro
      username: linkstar
      password: linkstar
      size: 10
      wait: yes
      wait_timeout: 1200
      vpc_security_groups: sg-7ab71302
      tags:
        Environment: dev
        Application: linkstar
    with_items: ec2_instances
    register: rds_result

  - name: run sqlline
    shell: sqlline -u jdbc:oracle:thin:@{{ item.instance.endpoint }}:1521:ORCL -n linkstar -p 1nsecure -d oracle.jdbc.driver.OracleDriver < /home/arlindo/projects/aws/files/createemp.sql
    with_items: "{{ rds_result.results|default([]) }}"

  - name: write rds host info to file
    local_action: 
      module: copy 
      content: "{{ item.instance.endpoint }}"
      dest: ./files/rdsendpoint.txt
    with_items: "{{ rds_result.results|default([]) }}"

#######

- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
    with_items: security_groups

  - name: Launch instances
    ec2: 
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ item.keypair }}"
      group: "{{ item.group }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ item.image }}"
      instance_tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      count_tag: "{{ item.count_tag }}"
      wait: yes
      wait_timeout: 500
    with_items: ec2_instances
    register: ec2_result

  - name: wait for WinRM to answer on all hosts
    wait_for:
      port: 5986
      host: "{{ item.tagged_instances[0].public_ip }}"
      timeout: 600
    with_items: "{{ ec2_result.results|default([]) }}"

  - name: add hosts to groups
    add_host:
      name: "win-temp-{{ item.tagged_instances[0].id }}"
      ansible_host: "{{ item.tagged_instances[0].public_ip }}"
      groups: win
    changed_when: false
    with_items: "{{ ec2_result.results|default([]) }}"

  - name: associate an elastic IP with an instance
    ec2_eip: 
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      device_id: "{{ item.tagged_instances[0].id }}"
      ip: 52.71.198.77
    with_items: "{{ ec2_result.results|default([]) }}"

########

- name: web app setup
  hosts: win
  gather_facts: no
  vars_files: [ "vars/aws-creds.yml" ]
  vars: 
    oraclerdsendpoint: "{{ lookup('file', './files/rdsendpoint.txt') }}"

  tasks:

  - name: ensure IIS and ASP.NET are installed
    win_feature:
      name: AS-Web-Support

  - name: Check to see if ODAC is installed
    win_stat: path='C:\oracle\client\product\12.1.0\client_1'
    register: odac_installed

  - name: Download ODAC
    win_get_url:
      url: 'https://github.com/sarlindo/odac/releases/download/v12.1.0/ODAC121024_x64.zip'
      dest: 'c:\users\administrator\appdata\local\temp\ODAC121024_x64.zip'
    when: not odac_installed.stat.exists

  - name: Unzip ODAC zip file
    win_unzip:
      src: C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64.zip
      dest: C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64
      creates: C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64
    when: not odac_installed.stat.exists

  - name: copy ODAC response file
    win_copy: src=./files/odacclient.rsp dest=C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64
    when: not odac_installed.stat.exists

  - name: Install ODAC
    raw: 'C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64\setup.exe -waitforcompletion -noconsole -silent -responseFile C:\Users\Administrator\AppData\Local\Temp\ODAC121024_x64\odacclient.rsp'
    when: not odac_installed.stat.exists

  - name: Install WebPI
    win_package:
      path="https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlatformInstaller_amd64_en-US.msi"
      Product_Id="{4D84C195-86F0-4B34-8FDE-4A17EB41306A}"
      Arguments="/quiet"

  - name: Install Web Deploy
    win_webpicmd:
      name: WDeploy

  - name: Download link star webapp
    win_get_url:
      url: 'https://github.com/sarlindo/linkstarasp/releases/download/v1.0/linkstarasp.zip'
      dest: 'c:\users\administrator\appdata\local\temp\linkstarasp.zip'

  - name: Unzip linkstar app zip file
    win_unzip:
      src: c:\users\administrator\appdata\local\temp\linkstarasp.zip
      dest: C:\app\sarlindo
      creates: C:\app\sarlindo\linkstarasp

# replace linkstar.cgxmjxhypelr.us-east-1.rds.amazonaws.com with oraclerdsendpoint
# C:\app\sarlindo\linkstarasp\Web.config
# (HOST=linkstar.cgxmjxhypelr.us-east-1.rds.amazonaws.com)

  - name: update web.config connection string
    win_lineinfile: 
      dest: C:\app\sarlindo\linkstarasp\Web.config
      regexp: \(HOST=.*\)
      line: connectionString="Provider=OraOLEDB.Oracle;Data Source=(DESCRIPTION=(CID=GTU_APP)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST={{ oraclerdsendpoint }})(PORT=1521)))(CONNECT_DATA=(SID=orcl)(SERVER=DEDICATED)));User Id=linkstar;Password=linkstar;"

  - name: Remove Default site
    win_iis_website:
      name: "Default Web Site"
      state: absent

  - name: LinkStar IIS site 
    win_iis_website: 
      name: "linkstarasp"
      state: started
      port: 80
      physical_path: 'c:\app\sarlindo\linkstarasp'
      parameters: 'logfile.directory:c:\app\sarlindo\linkstarasp\logs'
    register: linkstarwebsite

  - name: restart windows
    raw: 'powershell restart-computer -Force'
    when: not odac_installed.stat.exists

  - name: wait for windows system reboot
    local_action:
        module: wait_for
        port: 80
        host: "{{ ansible_host }}"
        timeout: 600
        delay: 30
    when: not odac_installed.stat.exists
